version: '3.5'

volumes:
  lam-app: 
  lam-data: 
  openldap-data:

networks:
  openldap-net:
    name: openldap-net
    driver: bridge
  web:
    external: true

services:
  ldap-mailcow:
    image: kaplan38/openldap-mailcow
    build: . 
    network_mode: host
    container_name: ldap-mailcow
    volumes:
        - ./data/ldap:/db:rw
        - ./data/conf/dovecot:/conf/dovecot:rw
        - ./data/conf/sogo:/conf/sogo:rw
    environment:
        - LDAP-MAILCOW_LDAP_URI=${LDAP_URL}
        - LDAP-MAILCOW_LDAP_BASE_DN=${LDAP_BASE_DN}
        - LDAP-MAILCOW_LDAP_BIND_DN=${LDAP_BIND_DN}
        - LDAP-MAILCOW_LDAP_BIND_DN_PASSWORD=${LDAP_BIND_DN_PASSWORD}
        - LDAP-MAILCOW_API_HOST=https://deneme.bul.com.tr
        - LDAP-MAILCOW_API_KEY=<YOUR-MAILCOW-API-KEY>
        - LDAP-MAILCOW_SYNC_INTERVAL=300
        #- LDAP-MAILCOW_LDAP_FILTER=(&(objectClass=posixAccount))
        #- LDAP-MAILCOW_SOGO_LDAP_FILTER=objectClass='posixAaccount'
        - LDAP-MAILCOW_LDAP_FILTER=(&(objectClass=inetOrgPerson))
        - LDAP-MAILCOW_SOGO_LDAP_FILTER=objectClass='inetOrgPerson'
  ldap-account-manager:
    image: ldapaccountmanager/lam:latest
    restart: unless-stopped
    volumes:
    - lam-data:/var/lib/ldap-account-manager/
    - lam-app:/etc/ldap-account-manager
    environment:
      # - LAM_PASSWORD=${LAM_PASSWORD}
      # - LAM_LANG=${LAM_LANG}
      # - LDAP_SERVER=${LDAP_SERVER}
      # - LDAP_DOMAIN=${LDAP_DOMAIN}
      # - LDAP_BASE_DN=${LDAP_BASE_DN}
      - ADMIN_USER=cn=${LDAP_ADMIN_NAME},${LDAP_BASE_DN}
      - LAM_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LAM_LANG=${LAM_LANG}
      - LDAP_SERVER=${LDAP_URL}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      # - ADMIN_USER=cn=admin,${LDAP_BASE_DN}
      # - DEBUG=true
    hostname: directory
    domainname: "${LDAP_DOMAIN}"
    networks:
      - openldap-net
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.openldap-lam.rule=Host(`directory.${LDAP_DOMAIN}`)
      - traefik.http.routers.openldap-lam.entrypoints=websecure
      - traefik.http.routers.openldap-lam.tls=true
      - traefik.http.routers.openldap-lam.tls.certresolver=myresolver
      - traefik.http.routers.openldap-lam.service=openldap-lam-svc
      - traefik.http.services.openldap-lam-svc.loadbalancer.server.port=80
      - traefik.http.routers.openldap-lam.middlewares=ldap-auth
      - traefik.http.middlewares.ldap-auth.basicauth.users=adam:$$2y$$05$$aio7rx3j9w87ky2uw9r

  certdumper:
    image: humenius/traefik-certs-dumper
    container_name: ldap_certdumper
    network_mode: none
    # env_file:
    #   - ldap.env
    volumes:
      # mount the folder which contains Traefik's `acme.json' file
      - ../../proxy/letsencrypt/:/traefik:ro
      - ./ldap/certs/:/output:rw
    environment:
      - DOMAIN=ldap.${LDAP_DOMAIN}

  # Bitnami OpenLDAP container (actively maintained)
  ldap:
    image: bitnami/openldap:latest
    ports:
      - '389:1389' # Expose port 389
    #   - '1636:1636'
    networks:
      - openldap-net
      - web
    volumes:
      - openldap-data:/bitnami/openldap
      - ./ldap/schemas:/schemas # Additional LDIF schemas
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.ldap.rule=Host(`ldap.${LDAP_DOMAIN}`)
      - traefik.http.routers.ldap.tls=true
      - traefik.http.routers.ldap.tls.certresolver=myresolver
      - traefik.http.routers.ldap.entrypoints=ldap
      - traefik.http.routers.ldap.service=ldap-svc
      - traefik.http.services.ldap-svc.loadbalancer.server.port=1389
    environment:
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_NAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ROOT=${LDAP_BASE_DN}
      - LDAP_SKIP_DEFAULT_TREE=${LDAP_SKIP_DEFAULT_TREE}
      - LDAP_GROUP=${LDAP_GROUP}
      - LDAP_USER_DC=${LDAP_USER_DC}
      - LDAP_CONFIG_ADMIN_ENABLED=${LDAP_CONFIG_ADMIN_ENABLED}
      - LDAP_CONFIG_ADMIN_USERNAME=${LDAP_CONFIG_ADMIN_NAME}
      - LDAP_CONFIG_ADMIN_PASSWORD=${LDAP_CONFIG_ADMIN_PASSWORD}
      - LDAP_LOGLEVEL=${LDAP_LOGLEVEL}
      - LDAP_PORT_NUMBER=${LDAP_PORT}
      - LDAP_USERS=${LDAP_USERS}
      - LDAP_PASSWORDS=${LDAP_PASSWORDS}

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/config.yml:/config.yml
      - ./data/letsencrypt:/letsencrypt
      - ./data/traefik.log:/traefik.log
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.tls.domains[0].main=
      - traefik.http.routers.traefik.tls.domains[0].sans=*.
      - traefik.http.routers.traefik.service=api@internal
